server:
  port: 8080
spring:
  mvc:
    pathmatch:
      matching-strategy: "ANT_PATH_MATCHER"
  datasource:
    url: jdbc:mysql://localhost:3306/gdou-gym
    username: root
    password: 1217
    driver-class-name: com.mysql.cj.jdbc.Driver
redis:
  host: 127.0.0.1
  port: 6379
  max-active: 200
  max-idle: 8
  min-idle: 0
